version: '3.2'
services:
  tmate:
    build:
      context: .
      args:
        uid: 1000
        usr: "${USER}"
    hostname: tmate
    privileged: true
    volumes:
      - ${HOME}/work:/home/${USER}/work:rw
      - ${HOME}/.gitconfig:/home/${USER}/.gitconfig:ro
      - ${HOME}/.vimrc:/home/${USER}/.vimrc:ro
      - ${HOME}/.ssh/id_rsa:/home/${USER}/.ssh/id_rsa:ro
